spring.application.name=certifyme

spring.datasource.url=jdbc:postgresql://db.vheafnqudxgjrfoarjee.supabase.co:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.vheafnqudxgjrfoarjee
spring.datasource.password=Sandilya@249
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.properties.hibernate.jdbc.batch_size=0

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# SERVER
server.port=8080

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true